// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: api/proto/searchv1/search.proto

package searchv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TopService_GetTop_FullMethodName = "/searchv1.TopService/GetTop"
)

// TopServiceClient is the client API for TopService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TopServiceClient interface {
	GetTop(ctx context.Context, in *GetTopRequest, opts ...grpc.CallOption) (*GetTopResponse, error)
}

type topServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTopServiceClient(cc grpc.ClientConnInterface) TopServiceClient {
	return &topServiceClient{cc}
}

func (c *topServiceClient) GetTop(ctx context.Context, in *GetTopRequest, opts ...grpc.CallOption) (*GetTopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTopResponse)
	err := c.cc.Invoke(ctx, TopService_GetTop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TopServiceServer is the server API for TopService service.
// All implementations must embed UnimplementedTopServiceServer
// for forward compatibility.
type TopServiceServer interface {
	GetTop(context.Context, *GetTopRequest) (*GetTopResponse, error)
	mustEmbedUnimplementedTopServiceServer()
}

// UnimplementedTopServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTopServiceServer struct{}

func (UnimplementedTopServiceServer) GetTop(context.Context, *GetTopRequest) (*GetTopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTop not implemented")
}
func (UnimplementedTopServiceServer) mustEmbedUnimplementedTopServiceServer() {}
func (UnimplementedTopServiceServer) testEmbeddedByValue()                    {}

// UnsafeTopServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TopServiceServer will
// result in compilation errors.
type UnsafeTopServiceServer interface {
	mustEmbedUnimplementedTopServiceServer()
}

func RegisterTopServiceServer(s grpc.ServiceRegistrar, srv TopServiceServer) {
	// If the following call panics, it indicates UnimplementedTopServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TopService_ServiceDesc, srv)
}

func _TopService_GetTop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopServiceServer).GetTop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopService_GetTop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopServiceServer).GetTop(ctx, req.(*GetTopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TopService_ServiceDesc is the grpc.ServiceDesc for TopService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TopService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "searchv1.TopService",
	HandlerType: (*TopServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTop",
			Handler:    _TopService_GetTop_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/searchv1/search.proto",
}

const (
	StopListService_ListStopWords_FullMethodName  = "/searchv1.StopListService/ListStopWords"
	StopListService_AddStopWord_FullMethodName    = "/searchv1.StopListService/AddStopWord"
	StopListService_DeleteStopWord_FullMethodName = "/searchv1.StopListService/DeleteStopWord"
)

// StopListServiceClient is the client API for StopListService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StopListServiceClient interface {
	ListStopWords(ctx context.Context, in *ListStopWordsRequest, opts ...grpc.CallOption) (*ListStopWordsResponse, error)
	AddStopWord(ctx context.Context, in *StopWordRequest, opts ...grpc.CallOption) (*StopWordResponse, error)
	DeleteStopWord(ctx context.Context, in *StopWordRequest, opts ...grpc.CallOption) (*StopWordResponse, error)
}

type stopListServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStopListServiceClient(cc grpc.ClientConnInterface) StopListServiceClient {
	return &stopListServiceClient{cc}
}

func (c *stopListServiceClient) ListStopWords(ctx context.Context, in *ListStopWordsRequest, opts ...grpc.CallOption) (*ListStopWordsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStopWordsResponse)
	err := c.cc.Invoke(ctx, StopListService_ListStopWords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stopListServiceClient) AddStopWord(ctx context.Context, in *StopWordRequest, opts ...grpc.CallOption) (*StopWordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopWordResponse)
	err := c.cc.Invoke(ctx, StopListService_AddStopWord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stopListServiceClient) DeleteStopWord(ctx context.Context, in *StopWordRequest, opts ...grpc.CallOption) (*StopWordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopWordResponse)
	err := c.cc.Invoke(ctx, StopListService_DeleteStopWord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StopListServiceServer is the server API for StopListService service.
// All implementations must embed UnimplementedStopListServiceServer
// for forward compatibility.
type StopListServiceServer interface {
	ListStopWords(context.Context, *ListStopWordsRequest) (*ListStopWordsResponse, error)
	AddStopWord(context.Context, *StopWordRequest) (*StopWordResponse, error)
	DeleteStopWord(context.Context, *StopWordRequest) (*StopWordResponse, error)
	mustEmbedUnimplementedStopListServiceServer()
}

// UnimplementedStopListServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStopListServiceServer struct{}

func (UnimplementedStopListServiceServer) ListStopWords(context.Context, *ListStopWordsRequest) (*ListStopWordsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListStopWords not implemented")
}
func (UnimplementedStopListServiceServer) AddStopWord(context.Context, *StopWordRequest) (*StopWordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddStopWord not implemented")
}
func (UnimplementedStopListServiceServer) DeleteStopWord(context.Context, *StopWordRequest) (*StopWordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteStopWord not implemented")
}
func (UnimplementedStopListServiceServer) mustEmbedUnimplementedStopListServiceServer() {}
func (UnimplementedStopListServiceServer) testEmbeddedByValue()                         {}

// UnsafeStopListServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StopListServiceServer will
// result in compilation errors.
type UnsafeStopListServiceServer interface {
	mustEmbedUnimplementedStopListServiceServer()
}

func RegisterStopListServiceServer(s grpc.ServiceRegistrar, srv StopListServiceServer) {
	// If the following call panics, it indicates UnimplementedStopListServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StopListService_ServiceDesc, srv)
}

func _StopListService_ListStopWords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStopWordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StopListServiceServer).ListStopWords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StopListService_ListStopWords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StopListServiceServer).ListStopWords(ctx, req.(*ListStopWordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StopListService_AddStopWord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopWordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StopListServiceServer).AddStopWord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StopListService_AddStopWord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StopListServiceServer).AddStopWord(ctx, req.(*StopWordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StopListService_DeleteStopWord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopWordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StopListServiceServer).DeleteStopWord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StopListService_DeleteStopWord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StopListServiceServer).DeleteStopWord(ctx, req.(*StopWordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StopListService_ServiceDesc is the grpc.ServiceDesc for StopListService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StopListService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "searchv1.StopListService",
	HandlerType: (*StopListServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListStopWords",
			Handler:    _StopListService_ListStopWords_Handler,
		},
		{
			MethodName: "AddStopWord",
			Handler:    _StopListService_AddStopWord_Handler,
		},
		{
			MethodName: "DeleteStopWord",
			Handler:    _StopListService_DeleteStopWord_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/searchv1/search.proto",
}
