// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: api/proto/searchv1/search.proto

package searchv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopRequest) Reset() {
	*x = GetTopRequest{}
	mi := &file_api_proto_searchv1_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopRequest) ProtoMessage() {}

func (x *GetTopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_searchv1_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopRequest.ProtoReflect.Descriptor instead.
func (*GetTopRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_searchv1_search_proto_rawDescGZIP(), []int{0}
}

func (x *GetTopRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type TopItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopItem) Reset() {
	*x = TopItem{}
	mi := &file_api_proto_searchv1_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopItem) ProtoMessage() {}

func (x *TopItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_searchv1_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopItem.ProtoReflect.Descriptor instead.
func (*TopItem) Descriptor() ([]byte, []int) {
	return file_api_proto_searchv1_search_proto_rawDescGZIP(), []int{1}
}

func (x *TopItem) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *TopItem) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetTopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*TopItem             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopResponse) Reset() {
	*x = GetTopResponse{}
	mi := &file_api_proto_searchv1_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopResponse) ProtoMessage() {}

func (x *GetTopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_searchv1_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopResponse.ProtoReflect.Descriptor instead.
func (*GetTopResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_searchv1_search_proto_rawDescGZIP(), []int{2}
}

func (x *GetTopResponse) GetItems() []*TopItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ListStopWordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStopWordsRequest) Reset() {
	*x = ListStopWordsRequest{}
	mi := &file_api_proto_searchv1_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStopWordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStopWordsRequest) ProtoMessage() {}

func (x *ListStopWordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_searchv1_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStopWordsRequest.ProtoReflect.Descriptor instead.
func (*ListStopWordsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_searchv1_search_proto_rawDescGZIP(), []int{3}
}

type ListStopWordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []string               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStopWordsResponse) Reset() {
	*x = ListStopWordsResponse{}
	mi := &file_api_proto_searchv1_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStopWordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStopWordsResponse) ProtoMessage() {}

func (x *ListStopWordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_searchv1_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStopWordsResponse.ProtoReflect.Descriptor instead.
func (*ListStopWordsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_searchv1_search_proto_rawDescGZIP(), []int{4}
}

func (x *ListStopWordsResponse) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

type StopWordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          string                 `protobuf:"bytes,1,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopWordRequest) Reset() {
	*x = StopWordRequest{}
	mi := &file_api_proto_searchv1_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopWordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopWordRequest) ProtoMessage() {}

func (x *StopWordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_searchv1_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopWordRequest.ProtoReflect.Descriptor instead.
func (*StopWordRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_searchv1_search_proto_rawDescGZIP(), []int{5}
}

func (x *StopWordRequest) GetTerm() string {
	if x != nil {
		return x.Term
	}
	return ""
}

type StopWordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          string                 `protobuf:"bytes,1,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopWordResponse) Reset() {
	*x = StopWordResponse{}
	mi := &file_api_proto_searchv1_search_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopWordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopWordResponse) ProtoMessage() {}

func (x *StopWordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_searchv1_search_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopWordResponse.ProtoReflect.Descriptor instead.
func (*StopWordResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_searchv1_search_proto_rawDescGZIP(), []int{6}
}

func (x *StopWordResponse) GetTerm() string {
	if x != nil {
		return x.Term
	}
	return ""
}

var File_api_proto_searchv1_search_proto protoreflect.FileDescriptor

const file_api_proto_searchv1_search_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/proto/searchv1/search.proto\x12\bsearchv1\"%\n" +
	"\rGetTopRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"5\n" +
	"\aTopItem\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"9\n" +
	"\x0eGetTopResponse\x12'\n" +
	"\x05items\x18\x01 \x03(\v2\x11.searchv1.TopItemR\x05items\"\x16\n" +
	"\x14ListStopWordsRequest\"-\n" +
	"\x15ListStopWordsResponse\x12\x14\n" +
	"\x05items\x18\x01 \x03(\tR\x05items\"%\n" +
	"\x0fStopWordRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\tR\x04term\"&\n" +
	"\x10StopWordResponse\x12\x12\n" +
	"\x04term\x18\x01 \x01(\tR\x04term2I\n" +
	"\n" +
	"TopService\x12;\n" +
	"\x06GetTop\x12\x17.searchv1.GetTopRequest\x1a\x18.searchv1.GetTopResponse2\xf2\x01\n" +
	"\x0fStopListService\x12P\n" +
	"\rListStopWords\x12\x1e.searchv1.ListStopWordsRequest\x1a\x1f.searchv1.ListStopWordsResponse\x12D\n" +
	"\vAddStopWord\x12\x19.searchv1.StopWordRequest\x1a\x1a.searchv1.StopWordResponse\x12G\n" +
	"\x0eDeleteStopWord\x12\x19.searchv1.StopWordRequest\x1a\x1a.searchv1.StopWordResponseB>Z<github.com/Karambollla/wb-search/api/proto/searchv1;searchv1b\x06proto3"

var (
	file_api_proto_searchv1_search_proto_rawDescOnce sync.Once
	file_api_proto_searchv1_search_proto_rawDescData []byte
)

func file_api_proto_searchv1_search_proto_rawDescGZIP() []byte {
	file_api_proto_searchv1_search_proto_rawDescOnce.Do(func() {
		file_api_proto_searchv1_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_searchv1_search_proto_rawDesc), len(file_api_proto_searchv1_search_proto_rawDesc)))
	})
	return file_api_proto_searchv1_search_proto_rawDescData
}

var file_api_proto_searchv1_search_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_searchv1_search_proto_goTypes = []any{
	(*GetTopRequest)(nil),         // 0: searchv1.GetTopRequest
	(*TopItem)(nil),               // 1: searchv1.TopItem
	(*GetTopResponse)(nil),        // 2: searchv1.GetTopResponse
	(*ListStopWordsRequest)(nil),  // 3: searchv1.ListStopWordsRequest
	(*ListStopWordsResponse)(nil), // 4: searchv1.ListStopWordsResponse
	(*StopWordRequest)(nil),       // 5: searchv1.StopWordRequest
	(*StopWordResponse)(nil),      // 6: searchv1.StopWordResponse
}
var file_api_proto_searchv1_search_proto_depIdxs = []int32{
	1, // 0: searchv1.GetTopResponse.items:type_name -> searchv1.TopItem
	0, // 1: searchv1.TopService.GetTop:input_type -> searchv1.GetTopRequest
	3, // 2: searchv1.StopListService.ListStopWords:input_type -> searchv1.ListStopWordsRequest
	5, // 3: searchv1.StopListService.AddStopWord:input_type -> searchv1.StopWordRequest
	5, // 4: searchv1.StopListService.DeleteStopWord:input_type -> searchv1.StopWordRequest
	2, // 5: searchv1.TopService.GetTop:output_type -> searchv1.GetTopResponse
	4, // 6: searchv1.StopListService.ListStopWords:output_type -> searchv1.ListStopWordsResponse
	6, // 7: searchv1.StopListService.AddStopWord:output_type -> searchv1.StopWordResponse
	6, // 8: searchv1.StopListService.DeleteStopWord:output_type -> searchv1.StopWordResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_searchv1_search_proto_init() }
func file_api_proto_searchv1_search_proto_init() {
	if File_api_proto_searchv1_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_searchv1_search_proto_rawDesc), len(file_api_proto_searchv1_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_proto_searchv1_search_proto_goTypes,
		DependencyIndexes: file_api_proto_searchv1_search_proto_depIdxs,
		MessageInfos:      file_api_proto_searchv1_search_proto_msgTypes,
	}.Build()
	File_api_proto_searchv1_search_proto = out.File
	file_api_proto_searchv1_search_proto_goTypes = nil
	file_api_proto_searchv1_search_proto_depIdxs = nil
}
